---
name: GrillSense Thermometer
version: 0.1.6
slug: grillsense
description: >-
  Monitor GrillSense/Dangrill WiFi BBQ thermometer temperatures
  and alarms via MQTT auto-discovery
url: https://github.com/bjornwein/grillsense
startup: application
boot: auto
init: false
host_network: true
hassio_api: true
hassio_role: default
services:
  - mqtt:want
auth_api: true
arch:
  - amd64
  - aarch64
options:
  mode: "local"
  udp_port: 17000
  device_name: "GrillSense Thermometer"
  device_mac: ""
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
schema:
  mode: list(local|cloud)
  udp_port: port
  device_name: str
  device_mac: str?
  mqtt_host: str?
  mqtt_port: port?
  mqtt_user: str?
  mqtt_pass: str?
image: ghcr.io/bjornwein/grillsense/{arch}
